"""empty message

Revision ID: 197ed66473ef
Revises: 74242ddae991
Create Date: 2017-06-15 22:08:25.289299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197ed66473ef'
down_revision = '74242ddae991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
