"""empty message

Revision ID: 74242ddae991
Revises: 7dab3b3ee9d8
Create Date: 2017-06-15 22:00:10.539797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74242ddae991'
down_revision = '7dab3b3ee9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('alias', sa.String(), nullable=False))
    op.create_index(op.f('ix_projects_alias'), 'projects', ['alias'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_alias'), table_name='projects')
    op.drop_column('projects', 'alias')
    # ### end Alembic commands ###
