"""empty message

Revision ID: e2f5759562dd
Revises: 593ffa36a4a4
Create Date: 2017-06-16 15:34:41.699262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f5759562dd'
down_revision = '593ffa36a4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_members_user_id_fkey', 'project_members', type_='foreignkey')
    op.drop_constraint('project_members_project_id_fkey', 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_assigments_task_id_fkey', 'task_assigments', type_='foreignkey')
    op.drop_constraint('task_assigments_user_id_fkey', 'task_assigments', type_='foreignkey')
    op.create_foreign_key(None, 'task_assigments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_assigments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_assigments', type_='foreignkey')
    op.drop_constraint(None, 'task_assigments', type_='foreignkey')
    op.create_foreign_key('task_assigments_user_id_fkey', 'task_assigments', 'users', ['user_id'], ['id'])
    op.create_foreign_key('task_assigments_task_id_fkey', 'task_assigments', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key('project_members_project_id_fkey', 'project_members', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('project_members_user_id_fkey', 'project_members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
